"""2nd migration

Revision ID: 4335fe003264
Revises: 7b2ef5b7ffc7
Create Date: 2025-02-23 12:38:41.285478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4335fe003264'
down_revision: Union[str, None] = '7b2ef5b7ffc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.drop_constraint('audit_logs_tenant_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'audit_logs', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('tenants', sa.Column('current_period_start', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('current_period_end', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('gateway_customer_id', sa.String(length=100), nullable=True))
    op.alter_column('tenants', 'plan',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('transactions', sa.Column('invoice_id', sa.String(length=100), nullable=True))
    op.add_column('transactions', sa.Column('receipt_url', sa.Text(), nullable=True))
    op.drop_constraint('transactions_user_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_tenant_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'transactions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'transactions', schema='public', type_='foreignkey')
    op.create_foreign_key('transactions_tenant_id_fkey', 'transactions', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key('transactions_user_id_fkey', 'transactions', 'users', ['user_id'], ['id'])
    op.drop_column('transactions', 'receipt_url')
    op.drop_column('transactions', 'invoice_id')
    op.alter_column('tenants', 'plan',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('tenants', 'gateway_customer_id')
    op.drop_column('tenants', 'current_period_end')
    op.drop_column('tenants', 'current_period_start')
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'audit_logs', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', schema='public', type_='foreignkey')
    op.create_foreign_key('audit_logs_tenant_id_fkey', 'audit_logs', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
